

MODULE COEFFICIENTS
IMPLICIT NONE


! xu0 is the value of U variable in previous time step

DOUBLE PRECISION:: RMASS(6) 

DOUBLE PRECISION, ALLOCATABLE,DIMENSION (:,:,:)::u0,xu0
DOUBLE PRECISION, ALLOCATABLE,DIMENSION (:,:,:)::ux,uy
DOUBLE PRECISION, ALLOCATABLE,DIMENSION (:,:,:)::uxx,uxy,uyy

!=========> RUNG KUTTA VARIABLES
DOUBLE PRECISION, ALLOCATABLE,DIMENSION (:,:,:)::u0_OLD
DOUBLE PRECISION, ALLOCATABLE,DIMENSION (:,:,:)::ux_OLD,uy_OLD
DOUBLE PRECISION, ALLOCATABLE,DIMENSION (:,:,:)::uxx_OLD,uxy_OLD
DOUBLE PRECISION, ALLOCATABLE,DIMENSION (:,:,:)::uyy_OLD

!=========> RIGHT HAND SIDE VALUE
DOUBLE PRECISION, ALLOCATABLE,DIMENSION (:,:,:)::right0
DOUBLE PRECISION, ALLOCATABLE,DIMENSION (:,:,:)::rightx,righty
DOUBLE PRECISION, ALLOCATABLE,DIMENSION (:,:,:)::rightxx,rightxy
DOUBLE PRECISION, ALLOCATABLE,DIMENSION (:,:,:)::rightyy

!=========> FLUX VALUES ON EDGE
DOUBLE PRECISION, ALLOCATABLE,DIMENSION (:,:,:,:)::fv_vedge     ! f_value  at 3 Gauss points,at vertical edge i+1/2,j 
DOUBLE PRECISION, ALLOCATABLE,DIMENSION (:,:,:,:)::fv_hedge     ! f_value  at 3 Gauss points,at horizontal edge i,j+1/2  
END MODULE