  
!****************************************************************
!*******INVISICD FLUX FUNCTIONS IN X-DIRECTIONS
!****************************************************************  

 FUNCTION F1(RHO,RHO_U,RHO_V,RHO_E)
 IMPLICIT NONE
 DOUBLE PRECISION :: F1
 DOUBLE PRECISION :: RHO,RHO_U,RHO_V,RHO_E
      F1=RHO_U 
 RETURN 
 END FUNCTION

 FUNCTION F2(RHO,RHO_U,RHO_V,RHO_E,GAMA)
 IMPLICIT NONE
 DOUBLE PRECISION :: F2
 DOUBLE PRECISION :: RHO,RHO_U,RHO_V,RHO_E,GAMA
 DOUBLE PRECISION :: U,V,E,P  
 U = RHO_U/RHO
 V = RHO_V/RHO
 P = (GAMA -1.0)*(RHO_E - 0.5*RHO*(U*U + V*V))
 f2=RHO*U*U + P
 RETURN 
 END FUNCTION


FUNCTION F3(RHO,RHO_U,RHO_V,RHO_E)
IMPLICIT NONE
DOUBLE PRECISION :: F3
DOUBLE PRECISION :: RHO,RHO_U,RHO_V,RHO_E
 F3=RHO_U*RHO_V/RHO  
RETURN 
END FUNCTION

      
FUNCTION f4(RHO,RHO_U,RHO_V,RHO_E,GAMA)
IMPLICIT NONE
DOUBLE PRECISION :: f4
DOUBLE PRECISION :: RHO,RHO_U,RHO_V,RHO_E,GAMA
DOUBLE PRECISION :: U,V,E,P  
 U = RHO_U/RHO
 V = RHO_V/RHO
 P = (GAMA -1.0)*(RHO_E - 0.5*RHO*(U*U + V*V))
 f4= (RHO_E + P)*U
RETURN 
END FUNCTION


!*************************************************************
!*************************************************************

FUNCTION G1(RHO,RHO_U,RHO_V,RHO_E)
IMPLICIT NONE
DOUBLE PRECISION :: G1
DOUBLE PRECISION :: RHO,RHO_U,RHO_V,RHO_E
      G1=RHO_V
RETURN 
END FUNCTION


FUNCTION G2(RHO,RHO_U,RHO_V,RHO_E)
IMPLICIT NONE
DOUBLE PRECISION :: G2
DOUBLE PRECISION :: RHO,RHO_U,RHO_V,RHO_E,GAMA
DOUBLE PRECISION :: U,V  
 U = RHO_U/RHO
 V = RHO_V/RHO
 G2=RHO*U*V 
RETURN 
END FUNCTION


FUNCTION G3(RHO,RHO_U,RHO_V,RHO_E,GAMA)
 IMPLICIT NONE
 DOUBLE PRECISION :: G3
 DOUBLE PRECISION :: RHO,RHO_U,RHO_V,RHO_E,GAMA
 DOUBLE PRECISION :: U,V,E,P  
 U = RHO_U/RHO
 V = RHO_V/RHO
 P = (GAMA -1.0)*(RHO_E - 0.5*RHO*(U*U + V*V))
 G3=RHO*V*V + P
 RETURN 
 END FUNCTION

FUNCTION G4(RHO,RHO_U,RHO_V,RHO_E,GAMA)
IMPLICIT NONE
DOUBLE PRECISION :: G4
DOUBLE PRECISION :: RHO,RHO_U,RHO_V,RHO_E,GAMA
DOUBLE PRECISION :: U,V,E,P  
 U = RHO_U/RHO
 V = RHO_V/RHO
 P = (GAMA -1.0)*(RHO_E - 0.5*RHO*(U*U + V*V))
 G4= (RHO_E + P)*V
RETURN 
END FUNCTION
